included prompt,if name, and asserts
nvega23/practice_problems pull request #8
Opened 2022-03-16 19:50 UTC by nvega23

2022-03-16 19:51 UTC, nvega23 commented
Even Fibonacci sequence

2022-03-18 05:10 UTC, kswang2400 requested changes

2022-03-18 05:10 UTC, kswang2400 commented on Even_Fibonacci.py
> +    print(tot)
nit: you can delete these

2022-03-18 05:10 UTC, kswang2400 commented on Even_Fibonacci.py
> +    return tot
are you sure any of these lines will ever run?

2022-04-06 15:16 UTC, kswang2400 approved these changes
looks awesome! great job!

2022-04-06 16:47 UTC, merged